version: '2'

services:
    # GLPI container
    glpi:
        build: .
        ports:
            - "8085:80"
        links:
            - mysql:db
        env_file:
            - ./glpi.env
        volumes:
            - glpi_data:/var/www/html/glpi

    # Database container
    mysql:
        image: mariadb
        env_file:
            - ./glpi.env
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    glpi_data: {}
    mysql_data: {}
